// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zebtdavyodbmkdhxhkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYnRkYXZ5b2RibWtkaHhoa2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxODE5MDcsImV4cCI6MjA1NTc1NzkwN30.QG7DqA4WfTlbzOmkQVxmnsxVWX83U4grQ2n8vFbGYLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);